### PR TITLE
Feature/add appveyor

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 build is failing. Is it due to AppVeyor? ping @opoudjis

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis I see 

```
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 4.4.0-101-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--save" "--save-exact" "puppeteer" "--unsafe-perm=true"
npm ERR! cwd /home/travis/build/metanorma/metanorma-nist
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/metanorma/metanorma-nist/npm-debug.log
npm ERR! not ok code 0
``` 

in logs looks like temporary issue, let me re-run

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis tests was broken in https://github.com/metanorma/metanorma-nist/commit/644f007f0a1703c4a4d375761cd82f666a2dbd01 commit, I will have a look

**Comment by opoudjis** [comment]
Let's see if the general gem push resolves this.

**Pull request merged**
